-- ============================================================
-- ADMINISTRATIONS — Bureau et administration d'une église
-- ============================================================

-- 1. TABLE ADMINISTRATIONS
create table if not exists public.administrations (
  id bigint generated by default as identity primary key,
  church_id bigint references public.churches(id) on delete cascade not null,
  member_id bigint references public.members(id) on delete cascade,
  function_title text not null,
  start_date date,
  end_date date,
  is_active boolean default true not null,
  notes text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Active Row Level Security
alter table public.administrations enable row level security;

-- 2. RLS POLICIES FOR ADMINISTRATIONS
-- RLS: lecture (select)
create policy "Users can view administrations of their churches" on public.administrations
  for select using (
    exists (
      select 1 from public.church_users cu
      where cu.church_id = administrations.church_id
      and cu.user_id = auth.uid()
    )
  );

-- RLS: insertion (insert)
create policy "Users can insert administrations in their churches" on public.administrations
  for insert with check (
    exists (
      select 1 from public.church_users cu
      where cu.church_id = administrations.church_id
      and cu.user_id = auth.uid()
    )
  );

-- RLS: mise à jour (update)
create policy "Users can update administrations in their churches" on public.administrations
  for update using (
    exists (
      select 1 from public.church_users cu
      where cu.church_id = administrations.church_id
      and cu.user_id = auth.uid()
    )
  );

-- RLS: suppression (delete)
create policy "Users can delete administrations in their churches" on public.administrations
  for delete using (
    exists (
      select 1 from public.church_users cu
      where cu.church_id = administrations.church_id
      and cu.user_id = auth.uid()
    )
  );

-- 3. TRIGGER FOR UPDATED_AT
create or replace function update_administrations_updated_at()
returns trigger as $$
begin
  new.updated_at = timezone('utc'::text, now());
  return new;
end;
$$ language plpgsql;

drop trigger if exists administrations_updated_at on public.administrations;
create trigger administrations_updated_at
  before update on public.administrations
  for each row execute procedure update_administrations_updated_at();

-- 4. PERFORMANCE INDEXES
create index if not exists idx_administrations_church_id on public.administrations(church_id);
create index if not exists idx_administrations_member_id on public.administrations(member_id);
