-- ============================================================
-- ANNEXES — Antennes / sous-groupes d'une église
-- ============================================================

-- 1. TABLE ANNEXES
create table if not exists annexes (
  id bigint generated by default as identity primary key,
  church_id bigint references churches(id) on delete cascade not null,
  name text not null,
  address text,
  description text,
  pastor_name text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table annexes enable row level security;

-- RLS: lecture
create policy "Users can view annexes of their churches" on annexes
  for select using (
    exists (
      select 1 from church_users cu
      where cu.church_id = annexes.church_id
      and cu.user_id = auth.uid()
    )
  );

-- RLS: insertion
create policy "Users can insert annexes in their churches" on annexes
  for insert with check (
    exists (
      select 1 from church_users cu
      where cu.church_id = annexes.church_id
      and cu.user_id = auth.uid()
    )
  );

-- RLS: mise à jour
create policy "Users can update annexes in their churches" on annexes
  for update using (
    exists (
      select 1 from church_users cu
      where cu.church_id = annexes.church_id
      and cu.user_id = auth.uid()
    )
  );

-- RLS: suppression
create policy "Users can delete annexes in their churches" on annexes
  for delete using (
    exists (
      select 1 from church_users cu
      where cu.church_id = annexes.church_id
      and cu.user_id = auth.uid()
    )
  );

-- Trigger updated_at
create or replace function update_annexes_updated_at()
returns trigger as $$
begin
  new.updated_at = timezone('utc'::text, now());
  return new;
end;
$$ language plpgsql;

drop trigger if exists annexes_updated_at on annexes;
create trigger annexes_updated_at
  before update on annexes
  for each row execute procedure update_annexes_updated_at();

-- ============================================================
-- 2. AJOUT DE annexe_id SUR LES TABLES EXISTANTES
-- (nullable pour ne pas casser les données existantes)
-- Chaque bloc vérifie que la table et la colonne existent avant d'agir.
-- ============================================================

-- members
do $$
begin
  if exists (select 1 from information_schema.tables where table_schema = 'public' and table_name = 'members') then
    if not exists (
      select 1 from information_schema.columns
      where table_schema = 'public' and table_name = 'members' and column_name = 'annexe_id'
    ) then
      alter table public.members add column annexe_id bigint references public.annexes(id) on delete set null;
    end if;
  end if;
end $$;

-- tithes
do $$
begin
  if exists (select 1 from information_schema.tables where table_schema = 'public' and table_name = 'tithes') then
    if not exists (
      select 1 from information_schema.columns
      where table_schema = 'public' and table_name = 'tithes' and column_name = 'annexe_id'
    ) then
      alter table public.tithes add column annexe_id bigint references public.annexes(id) on delete set null;
    end if;
  end if;
end $$;

-- offerings
do $$
begin
  if exists (select 1 from information_schema.tables where table_schema = 'public' and table_name = 'offerings') then
    if not exists (
      select 1 from information_schema.columns
      where table_schema = 'public' and table_name = 'offerings' and column_name = 'annexe_id'
    ) then
      alter table public.offerings add column annexe_id bigint references public.annexes(id) on delete set null;
    end if;
  end if;
end $$;

-- donations
do $$
begin
  if exists (select 1 from information_schema.tables where table_schema = 'public' and table_name = 'donations') then
    if not exists (
      select 1 from information_schema.columns
      where table_schema = 'public' and table_name = 'donations' and column_name = 'annexe_id'
    ) then
      alter table public.donations add column annexe_id bigint references public.annexes(id) on delete set null;
    end if;
  end if;
end $$;


-- ============================================================
-- 3. INDEX pour les performances (conditionnels)
-- ============================================================
create index if not exists idx_annexes_church_id on public.annexes(church_id);

do $$
begin
  if exists (select 1 from information_schema.columns where table_schema='public' and table_name='members' and column_name='annexe_id') then
    execute 'create index if not exists idx_members_annexe_id on public.members(annexe_id)';
  end if;
  if exists (select 1 from information_schema.columns where table_schema='public' and table_name='tithes' and column_name='annexe_id') then
    execute 'create index if not exists idx_tithes_annexe_id on public.tithes(annexe_id)';
  end if;
  if exists (select 1 from information_schema.columns where table_schema='public' and table_name='offerings' and column_name='annexe_id') then
    execute 'create index if not exists idx_offerings_annexe_id on public.offerings(annexe_id)';
  end if;
  if exists (select 1 from information_schema.columns where table_schema='public' and table_name='donations' and column_name='annexe_id') then
    execute 'create index if not exists idx_donations_annexe_id on public.donations(annexe_id)';
  end if;
end $$;


