-- ============================================================
-- EXPENSES — Dépenses d'une église
-- ============================================================

-- 1. TABLE EXPENSES
create table if not exists public.expenses (
  id bigint generated by default as identity primary key,
  church_id bigint references public.churches(id) on delete cascade not null,
  project_id uuid references public.projects(id) on delete set null,
  amount numeric not null check (amount >= 0),
  description text,
  paid_at date default current_date not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Active Row Level Security
alter table public.expenses enable row level security;

-- 2. RLS POLICIES FOR EXPENSES
-- RLS: lecture (select)
create policy "Users can view expenses of their churches" on public.expenses
  for select using (
    exists (
      select 1 from public.church_users cu
      where cu.church_id = expenses.church_id
      and cu.user_id = auth.uid()
    )
  );

-- RLS: insertion (insert)
create policy "Users can insert expenses in their churches" on public.expenses
  for insert with check (
    exists (
      select 1 from public.church_users cu
      where cu.church_id = expenses.church_id
      and cu.user_id = auth.uid()
    )
  );

-- RLS: mise à jour (update)
create policy "Users can update expenses in their churches" on public.expenses
  for update using (
    exists (
      select 1 from public.church_users cu
      where cu.church_id = expenses.church_id
      and cu.user_id = auth.uid()
    )
  );

-- RLS: suppression (delete)
create policy "Users can delete expenses in their churches" on public.expenses
  for delete using (
    exists (
      select 1 from public.church_users cu
      where cu.church_id = expenses.church_id
      and cu.user_id = auth.uid()
    )
  );

-- 3. TRIGGER FOR UPDATED_AT
create or replace function update_expenses_updated_at()
returns trigger as $$
begin
  new.updated_at = timezone('utc'::text, now());
  return new;
end;
$$ language plpgsql;

drop trigger if exists expenses_updated_at on public.expenses;
create trigger expenses_updated_at
  before update on public.expenses
  for each row execute procedure update_expenses_updated_at();

-- 4. PERFORMANCE INDEXES
create index if not exists idx_expenses_church_id on public.expenses(church_id);
create index if not exists idx_expenses_project_id on public.expenses(project_id);
create index if not exists idx_expenses_paid_at on public.expenses(paid_at);
