-- ============================================================
-- JOURNAL_ENTRIES — Journal de bord d'une église
-- ============================================================

-- 1. TABLE JOURNAL_ENTRIES
create table if not exists public.journal_entries (
  id bigint generated by default as identity primary key,
  church_id bigint references public.churches(id) on delete cascade not null,
  title text not null,
  category text,
  description text,
  occurred_at date default current_date not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Active Row Level Security
alter table public.journal_entries enable row level security;

-- 2. RLS POLICIES FOR JOURNAL_ENTRIES
-- RLS: lecture (select)
create policy "Users can view journal_entries of their churches" on public.journal_entries
  for select using (
    exists (
      select 1 from public.church_users cu
      where cu.church_id = journal_entries.church_id
      and cu.user_id = auth.uid()
    )
  );

-- RLS: insertion (insert)
create policy "Users can insert journal_entries in their churches" on public.journal_entries
  for insert with check (
    exists (
      select 1 from public.church_users cu
      where cu.church_id = journal_entries.church_id
      and cu.user_id = auth.uid()
    )
  );

-- RLS: mise à jour (update)
create policy "Users can update journal_entries in their churches" on public.journal_entries
  for update using (
    exists (
      select 1 from public.church_users cu
      where cu.church_id = journal_entries.church_id
      and cu.user_id = auth.uid()
    )
  );

-- RLS: suppression (delete)
create policy "Users can delete journal_entries in their churches" on public.journal_entries
  for delete using (
    exists (
      select 1 from public.church_users cu
      where cu.church_id = journal_entries.church_id
      and cu.user_id = auth.uid()
    )
  );

-- 3. TRIGGER FOR UPDATED_AT
create or replace function update_journal_entries_updated_at()
returns trigger as $$
begin
  new.updated_at = timezone('utc'::text, now());
  return new;
end;
$$ language plpgsql;

drop trigger if exists journal_entries_updated_at on public.journal_entries;
create trigger journal_entries_updated_at
  before update on public.journal_entries
  for each row execute procedure update_journal_entries_updated_at();

-- 4. PERFORMANCE INDEXES
create index if not exists idx_journal_entries_church_id on public.journal_entries(church_id);
create index if not exists idx_journal_entries_occurred_at on public.journal_entries(occurred_at);
create index if not exists idx_journal_entries_category on public.journal_entries(category);
