-- ============================================================
-- DONATIONS — Dons d'une église
-- ============================================================

-- 1. TABLE DONATIONS
create table if not exists public.donations (
  id bigint generated by default as identity primary key,
  church_id bigint references public.churches(id) on delete cascade not null,
  member_id bigint references public.members(id) on delete set null,
  project_id uuid references public.projects(id) on delete set null,
  donation_type text not null check (donation_type in ('money', 'physical')),
  amount numeric check (amount >= 0),
  physical_item text,
  donor_name text,
  payment_method text,
  reference text,
  notes text,
  received_at date default current_date not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Active Row Level Security
alter table public.donations enable row level security;

-- 2. RLS POLICIES FOR DONATIONS
-- RLS: lecture (select)
create policy "Users can view donations of their churches" on public.donations
  for select using (
    exists (
      select 1 from public.church_users cu
      where cu.church_id = donations.church_id
      and cu.user_id = auth.uid()
    )
  );

-- RLS: insertion (insert)
create policy "Users can insert donations in their churches" on public.donations
  for insert with check (
    exists (
      select 1 from public.church_users cu
      where cu.church_id = donations.church_id
      and cu.user_id = auth.uid()
    )
  );

-- RLS: mise à jour (update)
create policy "Users can update donations in their churches" on public.donations
  for update using (
    exists (
      select 1 from public.church_users cu
      where cu.church_id = donations.church_id
      and cu.user_id = auth.uid()
    )
  );

-- RLS: suppression (delete)
create policy "Users can delete donations in their churches" on public.donations
  for delete using (
    exists (
      select 1 from public.church_users cu
      where cu.church_id = donations.church_id
      and cu.user_id = auth.uid()
    )
  );

-- 3. TRIGGER FOR UPDATED_AT
create or replace function update_donations_updated_at()
returns trigger as $$
begin
  new.updated_at = timezone('utc'::text, now());
  return new;
end;
$$ language plpgsql;

drop trigger if exists donations_updated_at on public.donations;
create trigger donations_updated_at
  before update on public.donations
  for each row execute procedure update_donations_updated_at();

-- 4. PERFORMANCE INDEXES
create index if not exists idx_donations_church_id on public.donations(church_id);
create index if not exists idx_donations_member_id on public.donations(member_id);
create index if not exists idx_donations_project_id on public.donations(project_id);
create index if not exists idx_donations_received_at on public.donations(received_at);
create index if not exists idx_donations_type on public.donations(donation_type);
