-- ==========================================
-- Ajouter la gestion des documents
-- ==========================================

-- 1. Création de la table document_folders
CREATE TABLE IF NOT EXISTS public.document_folders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    church_id BIGINT NOT NULL REFERENCES public.churches(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Création de la table documents
CREATE TABLE IF NOT EXISTS public.documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    church_id BIGINT NOT NULL REFERENCES public.churches(id) ON DELETE CASCADE,
    folder_id BIGINT REFERENCES public.document_folders(id) ON DELETE SET NULL,
    name TEXT NOT NULL,
    description TEXT,
    file_path TEXT NOT NULL,
    file_url TEXT NOT NULL,
    file_type TEXT NOT NULL,
    file_size BIGINT NOT NULL,
    file_ext TEXT NOT NULL,
    is_public BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Activer RLS (Row Level Security)
ALTER TABLE public.document_folders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.documents ENABLE ROW LEVEL SECURITY;

-- 4. Politiques RLS pour document_folders
CREATE POLICY "Users can view their church document_folders" ON public.document_folders
    FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM public.church_users cu
            WHERE cu.church_id = document_folders.church_id
            AND cu.user_id = auth.uid()
        )
    );

CREATE POLICY "Users can manage their church document_folders" ON public.document_folders
    FOR ALL USING (
        EXISTS (
            SELECT 1 FROM public.church_users cu
            WHERE cu.church_id = document_folders.church_id
            AND cu.user_id = auth.uid()
        )
    );

-- 5. Politiques RLS pour documents
CREATE POLICY "Users can view their church documents" ON public.documents
    FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM public.church_users cu
            WHERE cu.church_id = documents.church_id
            AND cu.user_id = auth.uid()
        )
    );

CREATE POLICY "Users can manage their church documents" ON public.documents
    FOR ALL USING (
        EXISTS (
            SELECT 1 FROM public.church_users cu
            WHERE cu.church_id = documents.church_id
            AND cu.user_id = auth.uid()
        )
    );

-- Note Storage :
-- N'oubliez pas de créer manuellement un Bucket de stockage (Storage) nommé "church-documents"
-- dans l'interface Supabase, et d'y ajouter les règles de sécurité RLS (Storage Policies) :
-- SELECT, INSERT, UPDATE, DELETE autorisées pour les utilisateurs authentifiés.
