-- Enable UUID extension if not already enabled
create extension if not exists "uuid-ossp";

-- PROFILES (Public user data)
create table if not exists profiles (
  id uuid references auth.users(id) primary key,
  email text,
  full_name text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- CHURCHES (Already exists, but ensuring RLS)
create table if not exists churches (
  id bigint generated by default as identity primary key,
  name text not null,
  address text,
  phone text,
  email text,
  website text,
  logo_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Ensure logo_url exists if table was already created
do $$ 
begin 
  if not exists (select 1 from information_schema.columns where table_name = 'churches' and column_name = 'logo_url') then
    alter table churches add column logo_url text;
  end if;
end $$;

alter table churches enable row level security;

-- CHURCH_USERS (Link table for Many-to-Many relationship)
create table if not exists church_users (
  id bigint generated by default as identity primary key,
  church_id bigint references churches(id) on delete cascade not null,
  user_id uuid references auth.users(id) on delete cascade not null,
  role text default 'user' check (role in ('owner', 'admin', 'user')), -- High level role
  permissions jsonb default '{}'::jsonb, -- Granular permissions: { "members": ["view", "create"], "finances": ["view"] }
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(church_id, user_id)
);

alter table church_users enable row level security;

-- MEMBERS (Update RLS)
create table if not exists members (
  id bigint generated by default as identity primary key,
  church_id bigint references churches(id) on delete cascade not null,
  first_name text not null,
  last_name text not null,
  gender text check (gender in ('male', 'female', 'other')),
  phone text,
  email text,
  address text,
  dob date,
  status text default 'active' check (status in ('active', 'inactive', 'archived')),
  photo_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table members enable row level security;

-- POLICIES

-- 1. Profiles: Users can read all profiles (for invitations) but only update their own
create policy "Public profiles are viewable by everyone" on profiles for select using ( true );
create policy "Users can insert their own profile" on profiles for insert with check ( auth.uid() = id );
create policy "Users can update own profile" on profiles for update using ( auth.uid() = id );

-- 2. Church Users: Users can see churches they belong to
create policy "Users can view their own church memberships" on church_users 
  for select using ( auth.uid() = user_id );

-- 3. Churches: Users can view churches they are members of
create policy "Users can view churches they belong to" on churches 
  for select using ( 
    exists (
      select 1 from church_users cu 
      where cu.church_id = churches.id 
      and cu.user_id = auth.uid()
    )
  );

-- Allow public read access to churches for the registration page (only necessary fields ideally, but for simplicity: all)
create policy "Public can view basic church info" on churches
  for select using ( true );

create policy "Users can create churches" on churches for insert with check ( true );

-- 4. Members: Access depends on church_users connection
create policy "Users can view members of their churches" on members
  for select using (
    exists (
      select 1 from church_users cu
      where cu.church_id = members.church_id
      and cu.user_id = auth.uid()
    )
  );

create policy "Users can insert members to their churches" on members
  for insert with check (
    exists (
      select 1 from church_users cu
      where cu.church_id = members.church_id
      and cu.user_id = auth.uid()
    )
  );

create policy "Users can update members of their churches" on members
  for update using (
    exists (
      select 1 from church_users cu
      where cu.church_id = members.church_id
      and cu.user_id = auth.uid()
    )
  );

create policy "Users can delete members of their churches" on members
  for delete using (
    exists (
      select 1 from church_users cu
      where cu.church_id = members.church_id
      and cu.user_id = auth.uid()
    )
  );

-- GUESTS TABLE
create table if not exists guests (
  id bigint generated by default as identity primary key,
  church_id bigint references churches(id) on delete cascade not null,
  first_name text not null,
  last_name text not null,
  gender text check (gender in ('male', 'female', 'other')),
  phone text,
  email text,
  address text,
  visit_date date,
  invited_by text,
  follow_up_status text default 'pending' check (follow_up_status in ('pending', 'contacted', 'converted', 'not_interested')),
  notes text,
  photo_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table guests enable row level security;

-- GUESTS POLICIES
create policy "Users can view guests of their churches" on guests 
  for select using ( 
    exists (
      select 1 from church_users cu 
      where cu.church_id = guests.church_id 
      and cu.user_id = auth.uid()
    )
  );

create policy "Users can insert guests in their churches" on guests 
  for insert with check ( 
    exists (
      select 1 from church_users cu 
      where cu.church_id = guests.church_id 
      and cu.user_id = auth.uid()
    )
  );

create policy "Users can update guests in their churches" on guests 
  for update using ( 
    exists (
      select 1 from church_users cu 
      where cu.church_id = guests.church_id 
      and cu.user_id = auth.uid()
    )
  );

create policy "Users can delete guests in their churches" on guests 
  for delete using ( 
    exists (
      select 1 from church_users cu 
      where cu.church_id = guests.church_id 
      and cu.user_id = auth.uid()
    )
  );

-- Trigger to create profile on signup
create or replace function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.profiles (id, email, full_name)
  values (new.id, new.email, new.raw_user_meta_data->>'full_name');
  return new;
end;
$$ language plpgsql security definer;

-- Drop trigger if exists to avoid duplication error on re-run
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- RPC Function for Public Member Registration
-- This function allows anyone (even unauthenticated) to insert a member into a specific church
create or replace function register_member_via_link(
  p_church_id bigint,
  p_first_name text,
  p_last_name text,
  p_gender text,
  p_phone text,
  p_email text,
  p_address text
)
returns json
language plpgsql
security definer -- Bypass RLS
as $$
declare
  new_member_id bigint;
begin
  -- Validate inputs
  if p_first_name is null or p_last_name is null then
    raise exception 'First name and last name are required';
  end if;

  -- Insert member
  insert into members (church_id, first_name, last_name, gender, phone, email, address, status)
  values (p_church_id, p_first_name, p_last_name, p_gender, p_phone, p_email, p_address, 'active')
  returning id into new_member_id;

  return json_build_object('id', new_member_id, 'success', true);
end;
$$;
