-- ============================================================
-- MODULE GROUPES
-- ============================================================

-- 1. TYPES DE GROUPES
-- ============================================================
create table if not exists group_types (
  id bigint generated by default as identity primary key,
  church_id bigint references churches(id) on delete cascade not null,
  name text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table group_types enable row level security;

create policy "Users can view group types of their church" on group_types
  for select using (
    exists (
      select 1 from church_users cu
      where cu.church_id = group_types.church_id
      and cu.user_id = auth.uid()
    )
  );

create policy "Admins can insert group types" on group_types
  for insert with check (
    exists (
      select 1 from church_users cu
      where cu.church_id = group_types.church_id
      and cu.user_id = auth.uid()
      and cu.role in ('admin', 'owner')
    )
  );

create policy "Admins can update group types" on group_types
  for update using (
    exists (
      select 1 from church_users cu
      where cu.church_id = group_types.church_id
      and cu.user_id = auth.uid()
      and cu.role in ('admin', 'owner')
    )
  );

create policy "Admins can delete group types" on group_types
  for delete using (
    exists (
      select 1 from church_users cu
      where cu.church_id = group_types.church_id
      and cu.user_id = auth.uid()
      and cu.role in ('admin', 'owner')
    )
  );


-- 2. GROUPES
-- ============================================================
create table if not exists groups (
  id bigint generated by default as identity primary key,
  church_id bigint references churches(id) on delete cascade not null,
  group_type_id bigint references group_types(id) on delete set null,
  name text not null,
  description text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table groups enable row level security;

create policy "Users can view groups of their church" on groups
  for select using (
    exists (
      select 1 from church_users cu
      where cu.church_id = groups.church_id
      and cu.user_id = auth.uid()
    )
  );

create policy "Admins can insert groups" on groups
  for insert with check (
    exists (
      select 1 from church_users cu
      where cu.church_id = groups.church_id
      and cu.user_id = auth.uid()
      and cu.role in ('admin', 'owner')
    )
  );

create policy "Admins can update groups" on groups
  for update using (
    exists (
      select 1 from church_users cu
      where cu.church_id = groups.church_id
      and cu.user_id = auth.uid()
      and cu.role in ('admin', 'owner')
    )
  );

create policy "Admins can delete groups" on groups
  for delete using (
    exists (
      select 1 from church_users cu
      where cu.church_id = groups.church_id
      and cu.user_id = auth.uid()
      and cu.role in ('admin', 'owner')
    )
  );


-- 3. PERMISSIONS DES RESPONSABLES
-- (créée AVANT group_members pour éviter les références circulaires)
-- ============================================================
create table if not exists group_permissions (
  id bigint generated by default as identity primary key,
  group_id bigint references groups(id) on delete cascade not null,
  member_id bigint references members(id) on delete cascade not null,
  can_view boolean default true,
  can_add boolean default false,
  can_remove boolean default false,
  can_edit boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(group_id, member_id)
);

alter table group_permissions enable row level security;

create policy "Admins can view group permissions" on group_permissions
  for select using (
    exists (
      select 1 from groups g
      join church_users cu on cu.church_id = g.church_id
      where g.id = group_permissions.group_id
      and cu.user_id = auth.uid()
      and cu.role in ('admin', 'owner')
    )
  );

create policy "Admins can insert group permissions" on group_permissions
  for insert with check (
    exists (
      select 1 from groups g
      join church_users cu on cu.church_id = g.church_id
      where g.id = group_permissions.group_id
      and cu.user_id = auth.uid()
      and cu.role in ('admin', 'owner')
    )
  );

create policy "Admins can update group permissions" on group_permissions
  for update using (
    exists (
      select 1 from groups g
      join church_users cu on cu.church_id = g.church_id
      where g.id = group_permissions.group_id
      and cu.user_id = auth.uid()
      and cu.role in ('admin', 'owner')
    )
  );

create policy "Admins can delete group permissions" on group_permissions
  for delete using (
    exists (
      select 1 from groups g
      join church_users cu on cu.church_id = g.church_id
      where g.id = group_permissions.group_id
      and cu.user_id = auth.uid()
      and cu.role in ('admin', 'owner')
    )
  );


-- 4. MEMBRES D'UN GROUPE
-- (créée après group_permissions pour pouvoir y faire référence)
-- ============================================================
create table if not exists group_members (
  id bigint generated by default as identity primary key,
  group_id bigint references groups(id) on delete cascade not null,
  member_id bigint references members(id) on delete cascade not null,
  role text default 'member' check (role in ('member', 'leader')),
  joined_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(group_id, member_id)
);

alter table group_members enable row level security;

-- Admin/owner voit tout. Un responsable avec can_view voit son groupe.
create policy "Users can view group members" on group_members
  for select using (
    exists (
      select 1 from groups g
      join church_users cu on cu.church_id = g.church_id
      where g.id = group_members.group_id
      and cu.user_id = auth.uid()
      and (
        cu.role in ('admin', 'owner')
        or exists (
          select 1 from group_permissions gp
          where gp.group_id = group_members.group_id
          and gp.member_id = (
            select m.id from members m
            where m.church_id = g.church_id
            and m.email = auth.email()
            limit 1
          )
          and gp.can_view = true
        )
      )
    )
  );

create policy "Admins can insert group members" on group_members
  for insert with check (
    exists (
      select 1 from groups g
      join church_users cu on cu.church_id = g.church_id
      where g.id = group_members.group_id
      and cu.user_id = auth.uid()
      and cu.role in ('admin', 'owner')
    )
  );

create policy "Admins can update group members" on group_members
  for update using (
    exists (
      select 1 from groups g
      join church_users cu on cu.church_id = g.church_id
      where g.id = group_members.group_id
      and cu.user_id = auth.uid()
      and cu.role in ('admin', 'owner')
    )
  );

create policy "Admins can delete group members" on group_members
  for delete using (
    exists (
      select 1 from groups g
      join church_users cu on cu.church_id = g.church_id
      where g.id = group_members.group_id
      and cu.user_id = auth.uid()
      and cu.role in ('admin', 'owner')
    )
  );


-- 5. TRIGGER updated_at
-- ============================================================
create or replace function update_updated_at_column()
returns trigger as $$
begin
  new.updated_at = timezone('utc'::text, now());
  return new;
end;
$$ language plpgsql;

drop trigger if exists set_groups_updated_at on groups;
create trigger set_groups_updated_at
  before update on groups
  for each row execute procedure update_updated_at_column();

drop trigger if exists set_group_permissions_updated_at on group_permissions;
create trigger set_group_permissions_updated_at
  before update on group_permissions
  for each row execute procedure update_updated_at_column();
